/* Generated By:JavaCC: Do not edit this line. VNMConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VNMConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LESS = 5;
  /** RegularExpression Id. */
  int LE = 6;
  /** RegularExpression Id. */
  int GREAT = 7;
  /** RegularExpression Id. */
  int GE = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int NEQ = 10;
  /** RegularExpression Id. */
  int IN = 11;
  /** RegularExpression Id. */
  int NOTIN = 12;
  /** RegularExpression Id. */
  int PLUS = 13;
  /** RegularExpression Id. */
  int MINUS = 14;
  /** RegularExpression Id. */
  int PROD = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int ASSGN = 20;
  /** RegularExpression Id. */
  int LRND = 21;
  /** RegularExpression Id. */
  int RRND = 22;
  /** RegularExpression Id. */
  int LSQU = 23;
  /** RegularExpression Id. */
  int RSQU = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int SCOL = 26;
  /** RegularExpression Id. */
  int TRUE = 27;
  /** RegularExpression Id. */
  int FALSE = 28;
  /** RegularExpression Id. */
  int RANGE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int WHILE = 31;
  /** RegularExpression Id. */
  int FOR = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int THEN = 34;
  /** RegularExpression Id. */
  int ELIF = 35;
  /** RegularExpression Id. */
  int ELSE = 36;
  /** RegularExpression Id. */
  int FI = 37;
  /** RegularExpression Id. */
  int FUNCTION = 38;
  /** RegularExpression Id. */
  int RETURN = 39;
  /** RegularExpression Id. */
  int END = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int VAR = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int NUMBER = 45;
  /** RegularExpression Id. */
  int IDNUM = 46;
  /** RegularExpression Id. */
  int IDBOOL = 47;
  /** RegularExpression Id. */
  int IDVEC = 48;
  /** RegularExpression Id. */
  int IDMAT = 49;
  /** RegularExpression Id. */
  int STRING = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"=in\"",
    "\"!in\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"#1\"",
    "\"#0\"",
    "\"..\"",
    "\"DO\"",
    "\"WHILE\"",
    "\"FOR\"",
    "\"IF\"",
    "\"THEN\"",
    "\"ELIF\"",
    "\"ELSE\"",
    "\"FI\"",
    "\"FUNCTION\"",
    "\"RETURN\"",
    "\"END\"",
    "\"PRINT\"",
    "\"PRINTLN\"",
    "\"VAR\"",
    "<DIGIT>",
    "<NUMBER>",
    "<IDNUM>",
    "<IDBOOL>",
    "<IDVEC>",
    "<IDMAT>",
    "<STRING>",
    "<token of kind 51>",
  };

}
